from datetime import datetime, timezone
from typing import Dict, Any, Optional
from sqlalchemy.orm import Session
from app.models.models import (
    InfrastructureNode, Alert, Incident, IncidentPriority, IncidentStatus,
    AlertSeverity, HealthStatus, Notification, AuditLog, User
)
from app.services.ai_service import ai_service
from app.services.sla_service import calculate_sla_deadlines, calculate_priority

class AlertService:
    @staticmethod
    def process_metric_update(
        hostname: str,
        metric: str,
        value: float,
        db: Session
    ) -> Dict[str, Any]:
        """
        Process metric updates for an infrastructure node.
        If threshold crossed (e.g. CPU > 90%), triggers:
        1. Infrastructure Alert
        2. Automatic P1 Incident
        3. AI Analysis & Probable Cause
        4. Broadcast Notification
        5. Audit Log Entry
        """
        node = db.query(InfrastructureNode).filter(InfrastructureNode.hostname == hostname).first()
        if not node:
            return {"error": f"Node {hostname} not found"}

        # Update node metric
        if metric.upper() == "CPU":
            node.cpu_usage = value
        elif metric.upper() == "MEMORY":
            node.memory_usage = value
        elif metric.upper() == "DISK":
            node.disk_usage = value
        elif metric.upper() == "RESPONSE_TIME":
            node.response_time_ms = value
            
        node.last_ping = datetime.now(timezone.utc)
        
        # Check thresholds
        is_critical = value >= 90.0
        is_warning = value >= 75.0 and value < 90.0
        
        if is_critical:
            node.status = HealthStatus.CRITICAL
        elif is_warning:
            node.status = HealthStatus.WARNING
        else:
            node.status = HealthStatus.HEALTHY

        result = {
            "node": hostname,
            "status": node.status.value,
            "metric": metric,
            "value": value,
            "alert_created": False,
            "incident_created": False
        }

        # If critical and no open alert exists for this host, create Alert + Incident
        if is_critical:
            existing_alert = db.query(Alert).filter(
                Alert.resource_name == hostname,
                Alert.metric_name == metric,
                Alert.is_acknowledged == False
            ).first()
            
            if not existing_alert:
                alert_code = f"ALT-{int(datetime.now(timezone.utc).timestamp()) % 100000}"
                alert = Alert(
                    alert_code=alert_code,
                    source="Infrastructure Monitoring Engine",
                    resource_name=hostname,
                    metric_name=metric.upper(),
                    metric_value=value,
                    threshold_value=90.0,
                    severity=AlertSeverity.CRITICAL,
                    message=f"{hostname} {metric.upper()} exceeded 90% threshold (Current: {value:.1f}%).",
                    incident_created=True,
                    is_acknowledged=False
                )
                db.add(alert)
                db.flush()

                # Generate Incident
                inc_count = db.query(Incident).count() + 1001
                inc_num = f"INC-{inc_count}"
                alert.incident_number = inc_num
                
                title = f"Critical Infrastructure Failure: {hostname} {metric.upper()} Exceeded Threshold ({value:.1f}%)"
                description = (
                    f"Automated Alert generated by Telemetry Engine.\n\n"
                    f"Host: {hostname} ({node.ip_address})\n"
                    f"Environment: {node.environment}\n"
                    f"Metric: {metric.upper()} at {value:.1f}% (Threshold: 90.0%)\n"
                    f"Affected Service: {node.node_type} Subsystem\n"
                    f"Action Required: Investigate resource bottleneck, deadlock sessions, or scale node compute."
                )
                
                # AI Analysis
                ai_result = ai_service.analyze_incident(
                    title=title,
                    description=description,
                    category="Infrastructure",
                    impact="High",
                    urgency="High",
                    db=db
                )
                
                # Get default admin / system user as reporter
                admin_user = db.query(User).filter(User.username == "admin").first()
                reporter_id = admin_user.id if admin_user else 1

                resp_due, res_due = calculate_sla_deadlines(IncidentPriority.P1)

                incident = Incident(
                    incident_number=inc_num,
                    title=title,
                    description=description,
                    category="Infrastructure",
                    impact="High",
                    urgency="High",
                    priority=IncidentPriority.P1,
                    status=IncidentStatus.NEW,
                    reporter_id=reporter_id,
                    affected_service=f"{node.node_type} Layer",
                    sla_response_due=resp_due,
                    sla_resolution_due=res_due,
                    ai_probable_cause=ai_result["probable_cause"],
                    ai_recommendations="\n".join([f"{i+1}. {step}" for i, step in enumerate(ai_result["recommended_actions"])]),
                    ai_confidence=ai_result["confidence_score"],
                    ai_suggested_kb_ids="KB-104, KB-109",
                    ai_similar_incidents="INC-1001, INC-1007"
                )
                db.add(incident)
                db.flush()

                # Create Notification
                notification = Notification(
                    title=f"CRITICAL ALERT: {inc_num} Created",
                    message=f"{hostname} {metric.upper()} reached {value:.1f}%. P1 Incident {inc_num} automatically logged.",
                    notification_type="Alert",
                    severity="Critical",
                    link=f"/incidents/{incident.id}"
                )
                db.add(notification)

                # Create Audit Log
                audit = AuditLog(
                    user_id=reporter_id,
                    username="Telemetry Engine",
                    action="AUTOMATED_INCIDENT_CREATED",
                    resource_type="Incident",
                    resource_id=inc_num,
                    details=f"Automated P1 incident created for {hostname} metric spike ({metric}={value:.1f}%)"
                )
                db.add(audit)

                result["alert_created"] = True
                result["incident_created"] = True
                result["incident_number"] = inc_num
                result["alert_code"] = alert_code

        db.commit()
        return result

alert_service = AlertService()
